name: Build Goldleaf

on: [push, pull_request]

jobs:
  Goldleaf:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update packages
      run: |
        sudo -n apt-get update
        sudo -n apt-get upgrade -y patch autoconf automake diffutils pkgconf fakeroot git file tar bzip2 zstd
        sudo -n apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev curl software-properties-common
        wget https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz 
        tar -xf Python-3.9.0.tar.xz
        cd Python-3.9.0
        ./configure
        sudo make altinstall
        python3.9 -m pip install requests
        sudo -n dkp-pacman --noconfirm -U \
          "https://wii.leseratte10.de/devkitPro/other-stuff/dkp-toolchain-vars-1.0.2-1-any.pkg.tar.xz"

    - name: Silence all git safe directory warnings
      run: git config --system --add safe.directory '*'

    - name: Checkout latest libnx commit
      run: |
        git clone --recurse-submodules https://github.com/switchbrew/libnx.git

    - name: Set workspace permissions
      run: chmod 777 -R "$GITHUB_WORKSPACE"

    - name: Build and install libnx
      run: |
        cd libnx
        make install -j$(nproc)

    - name: Build libusbhsfs dependencies
      run: |
        cd libusbhsfs
        cd libntfs-3g; su -s /bin/bash nobody -c "dkp-makepkg -c -C -f" > /dev/null; sudo -n dkp-pacman -U --needed --noconfirm *.pkg.tar.* > /dev/null; cd ..
        cd liblwext4; su -s /bin/bash nobody -c "dkp-makepkg -c -C -f" > /dev/null; sudo -n dkp-pacman -U --needed --noconfirm *.pkg.tar.* > /dev/null; cd ..
        make BUILD_TYPE=GPL release

    - name: Build Goldleaf
      run: |
        python3.9 arc/arc.py gen_db default
        python3.9 arc/arc.py gen_cpp rc GLEAF Goldleaf/include/base_Results.gen.hpp
        make -j$(nproc)

    - uses: actions/upload-artifact@v3
      with:
        name: Goldleaf
        path: Goldleaf/Goldleaf.nro
        if-no-files-found: error
